- src/web-extension/manifest.json
> [#18] Opera: warning about missing permisisons

- spec/adapters/jira-spec.js
- src/common/adapters/jira.js
Attempt to fix #53 
Manually tested with jira and a recent chrome -- seems to fix the bug 🎉
> [#53] Copying issue name while name in selection mode works unexpected

- package.json
- spec/adapters/github-spec.js
- spec/adapters/gitlab-spec.js
- spec/adapters/jira-spec.js
- spec/adapters/pivotal-spec.js
- spec/adapters/trello-spec.js
- spec/support/helpers/setup.js
- src/common/adapters/gitlab.js
- yarn.lock
* attempt to fix #57 (tested it manually in a recent chrome and it seems to work on gitlab issue pages again)
* needed to update jsdom to access the `dataset` api in tests. including little fixes because of jsdom updates
* implemented the one leftover pending test for gitlab
> [#57] Stopped working with one of the recent gitlab updates

- spec/adapters/github-spec.js
- src/common/adapters/github.js
Lists all open tickets on github project pages.
> [#35] List github-project tickets

- README.md
- src/web-extension/manifest.json
A basic shortcut is actually not that hard. 
For more shortcuts we need to handle them correctly, but for now this does most of the trick.
> [#75] Keyboard shortcuts - basic

- package.json
- src/common/popup/components/about.jsx
- webpack.common.js
- yarn.lock
Remove the icon as a simple way out.
> [#97] Fix icon loading on about view

- yarn.lock
by updating ps-tree
This was the smallest change I could find to achieve that.
> Pin transitive dependency on event-stream

- src/safari-extension/Info.plist
- webpack.safari.babel.js
> [#107] Display extension version in Safari

- .circleci/config.yml
- .travis.yml
- README.md
> Switch to Circle CI

- .eslintrc.json
- package.json
- yarn.lock
https://github.com/jest-community/eslint-plugin-jest#rules
> Add Jest plugin for ESLint

- package.json
- yarn.lock
Ran into a build error on macOS Mojave. This fixes it.
> Upgrade node-sass to fix a build error on macOS

- src/common/adapters/github.js
- src/common/adapters/github.test.js
- src/common/adapters/gitlab.js
- src/common/adapters/gitlab.test.js
- src/common/adapters/jira.js
- src/common/adapters/jira.test.js
- src/common/adapters/ora.js
- src/common/adapters/ora.test.js
- src/common/adapters/pivotal.js
- src/common/adapters/pivotal.test.js
- src/common/adapters/trello.js
- src/common/adapters/trello.test.js
- src/common/popup/components/__snapshots__/no-tickets.test.jsx.snap
- src/common/popup/components/no-tickets.jsx
- src/common/popup/components/no-tickets.test.jsx
- src/common/popup/components/tool.jsx
- src/common/popup/components/tool.test.jsx
- src/common/popup/render.jsx
- src/common/popup/utils/error-shape.js
- src/common/search.js
- src/common/search.test.js
- src/common/utils/serializable-errors.js
- src/common/utils/serializable-errors.test.js
- src/safari-extension/popup/popup.js
- src/web-extension/background.js
- src/web-extension/popup/popup.js
Okay. So after a long wait, here's a first take on notifying users when something goes wrong while scanning for tickets. I have an idea for even better error reporting which I'll try out – but that'll be a separate PR.
> [#144] Handle adapter errors 

- README.md
I found the release process to be not documented currently. 
So I added some small instructions for it to the README :)
> Add some release documentation

- src/common/format/index.js
- src/common/format/index.test.js
> Slugify the ticket type in the branch formatter.

- src/common/adapters/github.js
- src/common/adapters/github.test.js
> [#154] Github tickety-tick issues seem to not work anymore

- src/web-extension/options/components/template-input.jsx
- src/web-extension/options/components/template-input.test.jsx
- src/web-extension/options/styles/_settings.scss
> [#165] Unable to copy default value in settings 

- README.md
Updates the section on keyboard shortcuts to output the keys using the
awesome [Keyboard Input HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd).
⬇️ looks like this (the rich diff) ⬇️
> Use keyboard input element in README

- src/web-extension/options/styles/_additions.scss
> Update Chrome options page layout

- .circleci/config.yml
- .stylelintrc.json
- README.md
- package.json
- src/options/index.scss
- src/options/styles/_additions.scss
- src/options/styles/_settings.scss
- src/popup/index.scss
- src/popup/styles/_additions.scss
- src/popup/styles/_settings.scss
- src/popup/styles/_spinner.scss
- yarn.lock
> Set up stylelint, update SCSS files

- README.md
Apparently forgot to adjust this in #239. 🤦
> Fix icon reference in README

- .circleci/config.yml
Extract executors & commands to make it easier to comprehend.
> Update Circle CI config to new version

- jest.config.js
- src/popup/index.js
- src/popup/index.test.js
I never really got around to testing this part of the codebase and was also wondering whether it'd be worth the effort. There are a few things going on in there though, so maybe it's a good idea?
I'm not 100% sure the way the tests are written is intuitive, so I am happy to hear about any thoughts you might have.
💚
> Test initialization code

- src/core/adapters/jira.js
- src/core/adapters/jira.test.js
Related to this [comment](https://github.com/bitcrowd/tickety-tick/issues/93#issuecomment-506907513)
Now the Jira adapter returns the ticket description and URL in the commit body.
---
By @klappradla and me
> [#93] Update Jira adapter

- README.md
- src/core/adapters/tara.js
- src/core/adapters/tara.test.js
- src/core/search.js
- src/popup/components/no-tickets.jsx
Hi everyone 👋 
Hope you're doing well! I recently started fiddling around with [tara.ai](https://app.tara.ai) for a side project and quickly realized manually keeping branch names and CLI commands in sync with what I've grown to love with `tickety-tick` was too painful. So I added a Tara adapter here.
I tried to follow practices used in other adapters closely and added documentation where I thought it was necessary.
___
Tara uses workspaces with multiple requirements, or projects, each. Task IDs are 1-based indices unique within each workspace (__not__ within the requirement). Page URLs follow the pattern: `https://app.tara.ai/<workspace-name>/tasks/<id>`.
The adapter extracts ticket information from the DOM. Given the obfuscated CSS classes, most context is retrieved from `data-cy` …
> Add tara ai support

- package.json
- src/popup/index.js
- yarn.lock
Use [`copy-text-to-clipboard`](https://github.com/sindresorhus/copy-text-to-clipboard) for copying to the clipboard instead of a custom implementation. This simplifies our code and the package takes care of some extra handling. :v:
> Use a package for copying to the clipboard

- src/popup/components/error-details.jsx
```
$ eslint --ignore-path .gitignore --ext .js,.jsx .
/tickety-tick/src/popup/components/error-details.jsx
35:23  warning  Unexpected console statement  no-console
```
> Fix linter warning (no-console).

- src/core/adapters/github.js
- src/core/adapters/github.test.js
> [#284] URL for Github issues

- src/options/components/form.jsx
- src/options/components/form.test.jsx
> Fix format preview on options page

- .circleci/config.yml
- safari/.swiftformat
- safari/tickety-tick Extension/SafariWebExtensionHandler.swift
- safari/tickety-tick.xcodeproj/project.xcworkspace/xcshareddata/IDETemplateMacros.plist
- safari/tickety-tick/AppDelegate.swift
- safari/tickety-tick/ViewController.swift
- Simplify Swift file header, configure template
- Format Swift code using SwiftFormat
- Configure CI check for Swift file formatting
> Clean up Safari extension code

- package.json
- src/core/enhance.js
- src/core/enhance.test.js
- src/core/format/__snapshots__/pretty-print.test.js.snap
- src/core/format/defaults.js
- src/core/format/helpers.js
- src/core/format/helpers.test.js
- src/core/format/index.js
- src/core/format/index.test.js
- src/core/format/pretty-print.js
- src/core/format/pretty-print.test.js
- src/core/format/template.js
- src/core/format/template.test.js
- src/options/components/form.jsx
- src/options/components/form.test.jsx
- yarn.lock
This reverts commit b76e7aa86b2cf022b61c3db0d10a91580aedc3d4.
…and brings back the formatter.
> Revert "Extracted formatter into its own package (#287)"

- jest.config.js
- package.json
- yarn.lock
~Based on #168.~
– https://github.com/jest-community/jest-watch-typeahead
> Add Jest watch plugins for better DX

- safari/tickety-tick.xcodeproj/project.pbxproj
- webpack.config.babel.js
Remove content-hash from `icon.svg` so the XCode project reference stays constant.
> Update Safari build

- README.md
#159
Update README with a short screencast of a possible workflow using Tickety-Tick 🍿
> [#159] Add a screencast to the readme

- README.md
- Update release instructions for tags
- Update release instructions for Firefox
> Small updates to docs

- README.md
- src/core/adapters/youtrack.test.ts
- src/core/adapters/youtrack.ts
Heya! 👋 I hope you're all doing great.
Here's a new adapter for [YouTrack](https://www.jetbrains.com/youtrack/).
_Disclaimer: I haven't tested this on a public cloud instance, configuration and markup might look slightly different there. But I guess we can improve support in case issues about this adapter do come in._
> Add adapter for YouTrack

- package.json
> Prepare v5.1.1

- package.json
> Prepare v5.2.0

- .circleci/config.yml
- package.json
- src/core/adapters/jira-cloud.test.ts
- tsconfig.json
This would have caught https://github.com/bitcrowd/tickety-tick/issues/406
> Run typecheck on CI

- package.json
> Prepare v5.2.1

- package.json
- src/options/components/template-input.test.tsx
- src/options/components/template-input.tsx
Some cleanups after the rather rushed bugfix release:
- Add typecheck to pre-release checks
- Update tests for template-input component
> Post release cleanups

- package.json
> Prepare v5.2.2

- src/core/adapters/clickup.test.ts
- src/core/adapters/clickup.ts
- src/core/search.ts
We use this now on a project and I am annoyed already.
https://app.clickup.com/
> Add clickup adapter

- package.json
> Prepare v5.3.0

- package.json
> Prepare v5.4.0

- package.json
> Prepare v5.5.0

- package.json
> Prepare v5.5.1
