src/common/popup/components/ticket-list.jsx

For an explanation on how tab order is determined, see:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
All ticket list copy buttons simply use tabindex="1" now.

[#22] tabIndex on first item

---

gulpfile.babel.js
spec/support/helpers/setup.js
src/common/adapters/github.js
src/common/adapters/jira.js
src/common/adapters/pivotal.js
src/common/adapters/trello.js
src/safari-extension/Info.plist
src/safari-extension/content.js
src/web-extension/content.js
src/web-extension/manifest.json

Use jQuery.noConflict(true) to avoid clashes with existing jQuery
instances on the content page. Looks a bit ugly and could be avoided by
bundling this and importing explicitely, buy hey… if that's what Mozilla
wants.

[#14] Extract jQuery/remove it

---

.eslintignore
.gitignore
.nycrc
.travis.yml
README.md
package.json

Sets up code coverage reporting using [istanbuljs/nyc](https://github.com/istanbuljs/nyc) and [coveralls.io](https://coveralls.io/).
- Requires a coveralls.io account to be set up (@bitboxer)
- badge is already added to the [`README.md`](https://github.com/bitcrowd/tickety-tick/blob/f4c7065828e15f8fcf890440ee05dc0b8965af84/README.md)
- Exclude `src/web-extension` and `src/safari-extension` directories from report?
- these directories contain files performing browser-specific entry points and hooks
- seems like the tests would just re-create what's already written in the implementation
- Test `src/common/popup/render.jsx`

Set up code coverage reporting

---

spec/popup/format-spec.js
src/common/popup/utils/format.js

Fixes #44. Thanks for reporting @tessi!
Background:
JavaScript `String.prototype.replace` can be called with a String or a RegExp as the first (match) argument. I expected the version with a String for matching to replace all occurrences, but apparently my memory tricked me.
Fix:
```js
s.replace('\'', '\'\\\'\'')
```
is now
```js
s.replace(/'/g, '\'\\\'\'')
```
Reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

[#44] Tickety is 'having' "problems" with correctly escaping 'quotes'

---

README.md

Removes hardcoded language slugs (`de` and `en`) from AMO and Opera Addons URLs.

Language agnostic URLs.

---

src/web-extension/manifest.json

Adds an extension ID as recommended by MDN:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Alternative_distribution_options/Sideloading_add-ons#Preparing_your_add-on

[#54] Extension can't be installed on new Firefox Quantum

---

README.md
gulpfile.babel.js
src/web-extension/manifest.json

Since the addon-ID is only needed when manually installing the plugin in newer versions
of firefox and also it is only needed if you want to install it permanently I added an env variable to activate the injection of the 'fake' addon ID. 
I put some references to #65

[#64] Warnings when installing with a recent chrome

---

package.json

Since we worked quite a lot on tickety-tick, I would try a new release also to finally achive 
#50.
Since the Firefox release seems to me to be the most crucial and hardest one, I will try and start with that one. 
before we can release however we need: 
In order to be in sync with the version numbers, I'd like to tick the number to 1.2.2, so we can later also release on chrome/opera.

release 1.2.2

---

package.json
spec/support/helpers/setup.js
src/common/adapters/github.js
src/common/adapters/helpers.js
src/common/adapters/jira.js
src/common/adapters/pivotal.js
src/safari-extension/Info.plist
src/safari-extension/content.js
src/web-extension/content.js
src/web-extension/manifest.json
webpack.common.js
yarn.lock

Based on changes in #71. Therefore needs to be rebased after that is merged and for review, focus on the commits starting at `[#72] …`.
Removes jQuery as a dependency. Instead implements adapter helpers using native DOM APIs.
See the links for detailed information on browser support and references to the MDN docs et cetera.
- [`Element.querySelector`/`querySelectorAll`](https://caniuse.com/#search=queryselector)
- [`Element.dataset`](https://caniuse.com/#search=dataset)
- [`Element.classList`](https://caniuse.com/#search=classlist)
- [`Element.getAttribute`](https://caniuse.com/#search=getattribute)
- [`Element.closest`](https://caniuse.com/#search=closest) (with a shim for DOM implementations that do not support it)
- `Element.textContent`
- …
Unit tests are passing, but we need to make …

[#72] Remove jQuery dependency

---

package.json
webpack.webext.babel.js
yarn.lock

While I was rerecording VCRs I thought I can quickly prepare the tickety-tick release :).
As we did have an auto-zip feature before with gulp and the files need to be uploaded as zip to the stores I also added that quickly. Webpack is awesome sometimes ❤️ .

[#79] Release 1.3

---

README.md
package.json
webpack.webext.babel.js
yarn.lock

Add an environment variable to conditionally zip the built extension
for WebExtension API-compatible browsers and two convenience npm scripts
for building releases:
```shell
yarn bundle:chrome
yarn bundle:firefox
```
Or, manually:
```shell
BUNDLE=true yarn build:firefox
```

Conditionally zip built web-extensions

---

package.json
webpack.common.js
yarn.lock

Add webpack plugin to show notifications on successful or failed builds.
This makes it easier to know when building has finished and you can
refresh, especially when you have the browser window open in the
foreground most of the time.
-- https://github.com/RoccoC/webpack-build-notifier

Add webpack-build-notifier

---

spec/adapters/jira-spec.js
src/common/adapters/jira.js

Enables finding tickets on the jira backlog view again. Also renames this within jira.js from `sidebar` to `backlog` which makes things a little more clear IMO

[#90] No tickets found on JIRA backlog view

---

src/safari-extension/Info.plist

The Tickety-Tick popup looked broken in Safari. Increasing the popup
width via the `Info.plist` apparently fixes the issue 🤷‍♂️ 
**Before**
**After**
The buttons still look a bit weird… I'll see whether I can follow up on this.

Fix popup layout in Safari

---

package.json

Fix a typo in the package.json passing an invalid option "productionp" instead of "production" as the mode to build the Firefox release 👋

Fix type in build command

---

README.md
package.json
spec/adapters/ora-spec.js
src/common/adapters/jira.js
src/common/adapters/ora.js
src/common/search.js

Add support for Ora. More specifically, allow Tickety-Tick to pick up information from opened tasks (information is extracted for single tasks that are opened in a model when clicking on them).
Addresses #110.

[#110] Add support for Ora

---

src/common/adapters/github.js
src/common/adapters/github.test.js
src/common/adapters/gitlab.js
src/common/adapters/gitlab.test.js
src/common/adapters/jira.js
src/common/adapters/jira.test.js
src/common/adapters/ora.js
src/common/adapters/ora.test.js
src/common/adapters/pivotal.js
src/common/adapters/pivotal.test.js
src/common/adapters/trello.js
src/common/adapters/trello.test.js
src/common/popup/render.jsx
src/common/search.js
src/common/search.test.js
src/safari-extension/content.js
src/safari-extension/popup/popup.js
src/web-extension/background.js
src/web-extension/content.js
src/web-extension/options/options.jsx
src/web-extension/popup/popup.js

**Description**
Make adapters async functions so they're more intuitive, e.g. with regard to fetching ticket info from a web API. Previously they used callback style with error and ticket arguments for the callback. However the error argument was never actually used/set.
Now, adapters should export an async `scan` function that receives the page `location` and `document` and returns an array of tickets.
Example: [github.js](https://github.com/bitcrowd/tickety-tick/blob/update-adapter-code/src/common/adapters/github.js)
Compared to the previous way of writing adapters: [github.js (old)](https://github.com/bitcrowd/tickety-tick/blob/871a8a34fb1581dbd579750fa57023be0888a2a8/src/common/adapters/github.js)
Hint: Enable "Hide whitespace changes" in the diff options 😉 
---
Intermediate issue …

Update adapter code

---

package.json
src/web-extension/background.js
src/web-extension/content.js
src/web-extension/options/components/form.jsx
src/web-extension/options/components/form.test.jsx
src/web-extension/options/components/template-input.test.jsx
src/web-extension/popup/popup.js
src/web-extension/store.js
yarn.lock

Adds [`mozilla/webextension-polyfill`](https://github.com/mozilla/webextension-polyfill).
This allows us to use the soon-to-be-standardized (according to the polyfill documentation and MDN), promise-based APIs across browsers.
We are using, for instance, [`storage.get()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get) and [`storage.set()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set).
Additionally, switching to the promise-based APIs also seems like an improvement, because we've updated our adapter code to use `async` & `await` and we now handle other asynchronous behavior in the same, consistent way.
Another small but nice side-effect is that we can drop some linting exceptions.

Use WebExtension polyfill to avoid browser compatibility issues

---

src/common/adapters/jira.js
src/common/adapters/jira.test.js

* Add support for self-hosted Jira instances (as long as they use the REST API)
* Tests that API requests are made against the correct endpoints/host
* Small refactoring

Additions for the new Jira adapter

---

.circleci/config.yml

The default maximum number of workers in Jest is equal to the number of
cores available on a machine. However, when running inside a Circle CI
Docker container, Jest sets this value to 35 causing tests to be slowed
down.
This commit explicitly sets the maximum number of workers to the actual
number of vCPUs for the Circle CI environment (2).
For a comparison:
- `test` job on master: https://circleci.com/gh/bitcrowd/tickety-tick/27#build-timing/containers/0/actions/102 — `Done in 11.34s.` (with test duration warnings)
- `test` job on this branch: https://circleci.com/gh/bitcrowd/tickety-tick/35#build-timing/containers/0 — `Done in 6.49s.`
References:
- Default Circle CI Docker executor has 2 vCPUs: https://circleci.com/docs/2.0/configuration-reference/#resource_class
- Jest using 35 …

Adjust number of Jest workers on Circle CI

---

src/common/adapters/jira.js
src/common/adapters/jira.test.js

It re-applies the changes introduced by #139 which has been deleted accidentally.

Update jira adapter to use rest endpoint 2

---

src/common/popup/popup.html
src/common/popup/popup.scss
src/common/popup/styles/_spinner.scss

Add a super simple, pure CSS spinner that is shown while tickets are being loaded.
**Preview**
_Note_: I added an extra timeout for demo purposes. In reality users should never see it this long.
Also, the slight stutter in the preview is due to the GIF framerate.

[#143] Add a loading indicator

---

webpack.common.js
webpack.safari.babel.js
webpack.webext.babel.js

Related to https://github.com/bitcrowd/tickety-tick/commit/d66f04c011021cf48c525717909fd071f71d7d6b
The `clean-webpack-plugin` is removing all files in the Webpack output
path on every rebuild in watch mode. At the same time however, the
`copy-webpack-plugin` only copies files once during the initial build
and after that only copies modified files by default.
This explicitly instructs the copy plugin to copy all files on every
rebuild so it is safe for the clean plugin to wipe the complete output
path.

Fix file copying in Webpack watch mode

---

.circleci/config.yml
.gitignore
package.json
yarn.lock

Set up Jest and ESLint to produce JUnit-compatible reports on Circle CI:
https://circleci.com/docs/2.0/collect-test-data/
This allows better timing and error reports in the Circle CI web interface and potentially insights into slow or flaky tests.

Collect test metadata

---

jest.config.js
package.json
src/common/__snapshots__/client.test.js.snap
src/common/adapters/jira.js
src/common/adapters/jira.test.js
src/common/client.js
src/common/client.test.js
yarn.lock

Update the JIRA adapter to fetch the ticket info via HTTP request instead of scraping the document.
Here's the documentation of the REST APIs: https://developer.atlassian.com/cloud/jira/software/rest/
I tested the changes both with Chrome and Firefox.
TODO:
Side notes:
- The package [`ky`](https://github.com/sindresorhus/ky) has been added and it is used as HTTP client

Update Jira adapter to use REST APIs for fetching ticket info

---

src/common/adapters/__helpers__/location.js
src/common/adapters/jira.test.js
src/common/adapters/trello.js
src/common/adapters/trello.test.js

Based on #137 
Here the documentation of the REST APIs: https://developers.trello.com/v1.0/reference#introduction
I tested the changes both with Firefox
**TODO:**

Update Trello adapter to use REST APIs for fetching ticket info

---

.eslintrc.json
jest.config.js
package.json
src/common/popup/components/__snapshots__/about.test.jsx.snap
src/common/popup/components/about.jsx
webpack.common.js
yarn.lock

Display the Git commit hash on the pop-up info screen and link to the
repo tree for that commit of the extension.

Show version information in pop-up

---

package.json
src/common/format/__snapshots__/pretty-print.test.js.snap
src/common/format/pretty-print.js
src/common/format/pretty-print.test.js
yarn.lock

Pretty-print commit messages according to recommendations:
https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
This isn't yet applied to the generated commit messages.
My idea was to add a checkbox to the options (enabled by default) to apply the recommended format to generated commit messages.
Let me know what you think 💚

[#93] Enhance commit messages (part 2)

---

src/web-extension/options/components/form.test.jsx

As you recently pointed out @lwassermann, a double-`find()` is not equivalent to `find()` + `filter()` as it will descend into child elements of the elements in the result set/wrapper.

Improve test code: Avoid unexpected elements

---

package.json
src/common/popup/components/__snapshots__/error-details.test.jsx.snap
src/common/popup/components/error-details.jsx
src/common/popup/components/error-details.test.jsx
src/common/popup/components/no-tickets.jsx
src/common/popup/utils/error-shape.js
src/common/utils/serializable-errors.js
src/common/utils/serializable-errors.test.js
yarn.lock

Here's an attempt at improving error reporting for adapter errors.
1. It uses the source-maps we ship with the bundled extension to create a clear stacktrace.
2. It allows users to easily copy the error message + stacktrace.
Ideally this makes it easier for users (including us) to provide more detailed issue descriptions.
To record this demo ☝️ I just inserted a `throw new Error('Boom!');` into the GitHub adapter.

[#144] Handle adapter errors (part 2)

---

src/common/adapters/jira.js
src/common/adapters/jira.test.js

Add next gen project url structure to regex of known url suffixes. These URLs look like this:
https://bitcrowd.atlassian.net/jira/software/projects/BCHP/boards/7?selectedIssue=BCHP-149
This fixes #195 
TODO:

[#195] Support backlog & board view of JIRA next gen software projects

---

yarn.lock

This updates the version of the `postcss-preset-env` package we use as a development dependency.
Background: running the tests showed the following deprecation warning:
> Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
The `caniuse-lite` is a dependency of the `postcss-preset-env` package - therefore I upgraded that.

Upgrade postcss-preset-env version

---

src/common/adapters/jira.js
src/common/adapters/jira.test.js

The JIRA board URLS changed for new JIRA boards. They now contain
optional trailing slashes and also allow further nested routes.
Examples:
* `/jira/software/projects/ABCD/boards/7`
* `/jira/software/projects/ABCD/boards/7/backlog`
Where before, only this URL was recognized:
* `/jira/software/projects/BCHP/boards/7/`
Closes #195.

Fix jira URL prefixes to work with new jira boards

---

package.json

Since bodo os not working at bitcrowd anymore, the mail address was out of date in package.json. This changes it to our tickety-tick address we use to register with the addon stores. Also it does not refer to a specific person anymore but all bitcrowd devs.

Update authors to be all of us

---

webpack.common.js
webpack.webext.babel.js

Set the cache option to false.
With the update to v4, the plugin otherwise won't re-generate our two
HTML files (popup and options) when in watch mode.

Update config for html-webpack-plugin

---

README.md
src/common/adapters/notion.js
src/common/adapters/notion.test.js
src/common/popup/components/no-tickets.jsx
src/common/search.js

This adds support for the [Notion](www.notion.so) tracker as beautifully prepared by @pmeinhardt in #163 🙏 💚 
Notion does not differentiate between "stories", "tasks", etc. For them, all actionable entites are **"pages"**. Tickety-Tick therefore also support creating branch names and commit messages for pages.
See here in action👇 
Please note: the board view is not an actionable "page" and therefore not supported by Tickety-Tick 🧑‍🏫 .
The commit messages for now only have a subject containing the rather long ID of the page and its title. For the page from the screencast this is:
**branch**
```
page/5b1d7dd7-9107-4890-b2ec-83175b8eda83-add-image-block
```
**message**
```
[#5b1d7dd7-9107-4890-b2ec-83175b8eda83] Add image…
…block
```
**command**
```
git checkout -b …
```

[#163] Please add notion.so support :)

---

src/common/adapters/github.js
src/common/adapters/gitlab.js
src/common/adapters/jira.js
src/common/adapters/jira.test.js
src/common/adapters/notion.test.js
src/common/adapters/trello.js
src/common/adapters/trello.test.js

Make use of Jest's automocking for automatically mocking the whole
`client` module with `jest.mock`. This automatically sets all exports of
the module to mock functions (jest.fn()).
Align the module level documentation to use multi-line comments.
[closes #225]

[#225] Clean up code comments and mocks

---

README.md

Add link to the docs for using Firefox' developer tools for debugging
extensions.
closes #228

[#228] Add debugging hints to README

---

src/common/popup/styles/_spinner.scss

This centers the spinner animation inside the popup window (see #230):
Thanks to @pmeinhardt for pointing to these nifty debugging tools 🧙‍♂️

[#230] Fix loading animation in new design

---

src/common/format/helpers.js
src/common/format/helpers.test.js
src/common/format/index.test.js
src/common/format/template.js
src/common/format/template.test.js
src/web-extension/options/components/form.jsx
src/web-extension/options/components/form.test.jsx

I was intrigued @bitboxer and had a moment this morning to throw something together.
It allows for (optionally) parameterized filters in templates, e.g.:
```
Title is "{value | truncate(50)}"
```
I've also changed how we handle errors in template expressions, hoping to make it easier to figure out what's going wrong in case of typos and erroneous templates. For instance:
- The above template will now return `Title is "!!(no helper named "truncate")"` if a `truncate` helper doesn't exist
- For a template `…{value | truncate(crash)}` it will return `…!!(invalid parameters provided to "truncate": crash)`
From what I can see, there's at least two more to-dos:
Please take it for a spin when you have time.
Happy about feedback. 🙂 
Closes #233.

[#233] New helper to limit string length 

---

MAINTAINERS.md
README.md
package.json

This addresses #212: Firefox by default does no longer allow to permanently install unsigned extensions.
Therefore, I added a `yarn sign` script for self-signing "unlisted" beta version of the extension via `web-ext` (we will most likely run this from CI in the future). According to the docs and experience on the internet, the `sign` command is not yet ready for _"listed"_ extensions. It may be possible to to both though: submit the same version as "listed" and "unlisted". We probably want to do this if we _(what I would suggest)_ also want to give people the option install the extension from a file.
I also updated the docs on that topic and will update the instructions in 1password in a minute.

[#212] Add 'sign' script and update Firefox docs

---

src/popup/components/external-link.jsx
src/popup/components/external-link.test.jsx
src/popup/env-context.jsx
src/popup/index.js

Based on top of #239 (rebase + change base branch to `master` after merging that one).
The `openext` function passed down through the React element hierarchy was originally introduced to fix an issue with opening external links from the popup in Safari. With Tickety-Tick dropping support for Safari it is no longer needed.
See `src/safari-extension/popup/popup.jsx` in commit ed881e4.

Remove openext function, simplify external links

---

src/core/enhance.js
src/core/enhance.test.js
src/core/format/defaults.js
src/core/format/index.js
src/options/components/form.jsx
src/options/components/form.test.jsx

With the more focused extension design in v4, we no longer have the "Summary" feature. This removes the format + options page code for it.
Based on #239. (If we decide not to merge 239 or to postpone it, we should "backport" these changes onto `master` befoer releasing `v4.0.0`).

Remove now unused summary format

---

src/manifest.json

Closes #256.
Removing the `clipboardRead` permission seems to not cause any problems.

[#256] Update the list of permissions

---

package.json
src/options/components/form.jsx
src/popup/components/__snapshots__/about.test.jsx.snap
src/popup/components/about.jsx
src/popup/components/ticket-controls.jsx
src/popup/styles/_additions.scss
yarn.lock

Closes #257.
~Based on #262.~
The chevron color is fixed.
Also, the octicons package is upgraded to the most recent version.
This means the icons now look slightly different (as in GitHub's new design).

[#257] Fix "back" chevron color

---

src/core/adapters/gitlab.js
src/core/adapters/gitlab.test.js

Implements a new approach to extract the ticket id from a GitLab issue page. The previously used id `js-issuable-app-initial-data` is no longer present in the source. However the legacy approach is left in place to support older self-hosted GitLab installations.
I tested the development build with Chrome on the GitLab page to confirm it's working.
Closes #270

[#270] GitLab integration is broken

---

src/popup/components/__snapshots__/about.test.jsx.snap
src/popup/components/about.jsx
src/popup/components/navbar.jsx
src/popup/components/tool.jsx
src/popup/components/tool.test.jsx
src/popup/env-context.jsx
src/popup/index.js
src/popup/index.test.js
src/popup/styles/settings/_common.scss

During a pair-programming session with @nickgnd, I noticed that it takes a little too long to navigate to the extension settings when you just want to quickly make some adjustments.
This adds a link to the popup to open the options page. ✌️

Add link to open extension settings to popup

---

src/manifest.json

Tested on Chrome 88 and FF 82. Ticket is recognized both when clicking
the extension icon and when pressing Ctrl+T.
Unfortunately wasn't able to find reliable information as to when support
for `activeTab` was added to the respective browsers, but at least all
current versions support it.
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission
* https://developer.chrome.com/docs/extensions/mv2/manifest/activeTab/
* https://dev.opera.com/extensions/declare-permissions/
* https://developer.apple.com/documentation/safariservices/safari_web_extensions/managing_safari_web_extension_permissions
Further restricting the permissions to hosts (e.g. `github.com`) would
make sense for cloud services, but could be difficult for …

[#269] Switch to activeTab permission

---

README.md

Scrolling through the README I noticed https://github.com/bitcrowd/tickety-tick/commit/10b64df286d8a1e54bf77eaf5876f8ef2d0fd2ea introduced a "Settings" link to Tickety-Tick's popup which can be used to more easily navigate to the preferences page. This updates the "advanced configuration" README section to describe this quicker way of getting there.

Update "advanced configuration" README section

---

yarn.lock

Upgrade `cssnano` to iron out the open security vulnerability in `is-svg`.
See: https://github.com/advisories/GHSA-7r28-3m3f-r2pr

Upgrade cssnano

---

src/popup/components/copy-button.jsx
src/popup/components/copy-button.test.jsx
src/popup/components/tool.jsx
src/popup/components/tool.test.jsx
src/popup/env-context.jsx
src/popup/index.js
src/popup/index.test.js
src/popup/render.jsx

We no longer have different entry points for Safari and other browsers.
We can drop the formerly browser-specific `EnvContext` and simplify the
setup.

Remove env context

---

yarn.lock

Resolves an issue with the formatter not honoring custom templates.
See https://github.com/bitcrowd/tickety-tick-formatter/pull/5

Upgrade tickety-ticket-formatter

---

yarn.lock

Upgrade `hosted-git-info` again (this time to 3.0.8).
See: https://github.com/advisories/GHSA-43f8-2h32-f4cj

Fix CVE-2021-23362

---

package.json
yarn.lock

This fixes [CVE-2021-32640](https://github.com/advisories/GHSA-6fc8-4gx4-v693), a security vulnerability in `ws`.

Upgrade web-ext package

---

script/extract-cert-ou

When using the script `script/extract-cert-ou` with another locale than en (e.g., de), the owner of the certificate can not be found ("Aussteller" vs. "Owner").

Explcitly set the language for the exported cert to en

---

README.md
src/options/components/template-input.tsx
src/options/index.html
src/options/styles/_additions.scss

Apply a character-maximum width to the preview sections of the form. This stops Chrome from making the dialog grow forever.
Side-party 🎉: also add a note about debugging the options page in Chrome to the README (thanks @ArinzeJeffrey-droid)
Closes: #331

[331] Chrome setting screen is growing forever

---

README.md
src/core/adapters/linear.test.ts
src/core/adapters/linear.ts
src/core/search.ts
src/popup/components/__snapshots__/no-tickets.test.tsx.snap
src/popup/components/no-tickets.tsx

Adds a simple, DOM based [Linear](https://linear.app/) adapter.
The selectors are fragile (because Linear minimizes their CSS so we can't use their CSS classes) and will require updating if Linear adds more languages.
I had a few issues locally:
1. after running any tasks that create `dist/` the path is picked up by `yarn test` which produces a lot of confusing test failures
1. (_this is only an issue if one doesn't want to install Rosetta_) the build system uses some notifiers that come with pre-built x86 executables for `terminal-notifier`. Those will crash on arm64 (Apple M1). Since `terminal-notifier` seems unmaintained, as a (very) dirty work-around one can compile `terminal-notifier` to get an arm64 executable (for example via `brew`) and use that binary instead:
```
brew install …
```

Add Linear.app adapter

---

package.json
src/popup/components/__snapshots__/no-tickets.test.tsx.snap
src/popup/components/no-tickets.test.tsx
yarn.lock

Some small cleanup fixes and updates.
Changes:
- Fix warning in tests
We were nesting a `ul` element into a `p` element - which is invalid. As this was only within a mock, I just changed the mock to a plain `span` which renders the list inline.
- Update browserlist
- Upgrade web-ext package
This should free the path to more dependency updates.

Small fixes and updates

---

package.json
webpack.config.babel.js
yarn.lock

[337](https://github.com/bitcrowd/tickety-tick/issues/337)
Remove the `webpack-build-notifier` package. It relies on unmaintained packages which aren't compatible with M1 Macs out of the box any more.

[337] Remove terminal notification setup

---

.circleci/config.yml

Use the faster next gen image for NodeJS.
See [this blog post](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/) for a reference.
Unfortunately, for the Swift image we're using, Circle does not have their own images.

Update CI base image

---

package.json
yarn.lock

Fix a vulnerability on nth-check
https://github.com/gregberge/svgr/pull/609
https://nvd.nist.gov/vuln/detail/CVE-2021-3803
Icons still work (on chrome):

Upgrade svgr/webpack to fix CVE-2021-3803

---

package.json
yarn.lock

[348](https://github.com/bitcrowd/tickety-tick/issues/348)
This updates the `mdast-util-from-adf` to [v2.1.0](https://github.com/bitcrowd/mdast-util-from-adf/releases/tag/v2.1.0) which adds support for `epand` notes in Jira.
The title of the expand section is ignored and the content just added to the normal document flow. Can you check if that fixes #348 for you @agatheblues?
Special thanks to @pmeinhardt 💚

[348] Error: unsupported node type "expand"

---

package.json
yarn.lock

This updates webpack-cli to v5 and webpack (while I was already on it). Motivation for this is, that webpack-cli v4 is broken with the current LTS Node JS version.
See https://github.com/webpack/webpack/issues/14532
This is the error one runs into with the previous version:
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at BulkUpdateDecorator.hashFactory (/home/circleci/tickety-tick/node_modules/webpack/lib/util/createHash.js:155:18)
at BulkUpdateDecorator.update (/home/circleci/tickety-tick/node_modules/webpack/lib/util/createHash.js:46:50)
at SourceMapSource.updateHash (/home/circleci/tickety-tick/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
at …
```

Update webpack-cli package

---

src/core/adapters/notion.test.ts
src/core/adapters/notion.ts

This PR adds the URL to a ticket in the Notion adapter. It will work on both the ticket show and the board view (modal). It relies on Notion redirecting from `/id` to `/slug`.
https://github.com/bitcrowd/tickety-tick/issues/362

[#362] Expose notion page url

---

src/core/adapters/notion.test.ts
src/core/adapters/notion.ts

Removes dependence on :organization in ticket path
https://github.com/bitcrowd/tickety-tick/issues/369

[#369] Support notion pages without organizations

---

src/core/adapters/github.test.ts
src/core/adapters/github.ts

This updates the GitHub adapter for the new Markup GitHub uses for labels on issues. With this change, issues labelled as "bug" should again result into a branch name like `bug/xyz/`.
On the side, this also removes the code for selecting issues on GitHub project pages. GitHub projects are entities on the user/organization now, not part of a repository. If we want to support them, it needs to be done differently. There's a follow up issue for that #403.

[401] Fix GitHub adapter bug label detection

---

package.json
yarn.lock

An issue in the web-ext package was preventing Firefox from opening in
development. Upgrading the package fixed the problem.
For reference, see https://github.com/mozilla/web-ext/issues/2975

Fix dev setup for Firefox

---

package.json
yarn.lock

Update `mdast-util-from-adf` package.
Updating the other `mdast` packages requires some more changes as they pretty much all moved to ES modules. Will do separate PRs for that.

Update mdast-util-from-adf dependency

---

package.json
src/background/index.ts
src/content/index.ts
src/manifest.json
src/popup/index.test.ts
src/popup/index.ts
src/popup/types.ts
webpack.config.babel.js
yarn.lock

This fixes #311 and migrates the extension to use [Manifest v3](https://developer.chrome.com/docs/extensions/develop/migrate/what-is-mv3). The most important change from v2 to v3 is that Firefox and Safari use background scripts or background pages while Chrome uses service workers for any background activity. They don't have a common ground though: Firefox & Safari extensions do not support background service workers and Chrome extensions do not support background pages or scripts.
So the respective `background` key in the `manifest.json` file accepts both, `scripts` and `service_worker` while the browsers only read what they can understand.
Tickety-Tick used a background script to load the ticket information from the current tab if there's any. Doing so it was using a global function …

[311] Mozilla Add-ons manifest v3

---

SAFARI.md

Tiny doc-change for Safari instructions. The build works and the
installed extension is also persisted. The only thing that was necessary
for me was to install a new version of Java…
Fixes #360

[360] Check Safari build setup

---

package.json
src/content/index.ts
src/polyfills.ts
yarn.lock

Polyfill Headers for Firefox
There is an issue with Manifest v3 in Firefox, that the global Headers
class does not work anymore (it did in Manifest v2). Therefore we're
overriding the global window.Headers to use a polyfill.
Doing so, `ky` can do it's header merging thing and our HTTP client works 🎉.
Fixes #432

[432] Firefox Jira adapter broken with manifest v3

---

README.md
src/core/adapters/plane.test.ts
src/core/adapters/plane.ts
src/core/search.ts
src/popup/components/__snapshots__/no-tickets.test.tsx.snap
src/popup/components/no-tickets.tsx

This PR adds an adapter to extract issue information from (self-hosted) [Plane](https://plane.so) instances. It extracts information from the url and the title tag and works from the issue detail page.

feat: add support for plane

---

src/core/adapters/dom-helpers.ts
src/core/adapters/github.test.ts
src/core/adapters/github.ts

This updates the GitHub adapter to work with the redesigned issue pages.
As we do not know now GitHub Enterprise looks like for the majority of
users, we keep the previous logic for the "legacy" strategy of the
adapter.
To keep the change and the adapter simple, I dropped support selecting
issues on the issues page. Instead, we only support the issue show pages
now. On the long run, it may make sense to look into supporting GitHub
projects too.
The new GitHub adapter supports GitHub issue types and won't look for
the "bug" label any more.
Ticket: https://github.com/bitcrowd/tickety-tick/issues/443
Fixes: #443

[#443] Fix GitHub adapter broken after GitHub redesign

---

src/options/components/template-input.tsx

This fixes the preview of the branch name format in the settings form.
Fixes #442
https://github.com/bitcrowd/tickety-tick/issues/442

[#442] Fix branch name preview in settings
